### ISSUE TITLE
IE has touch supported?

### ISSUE THREAD

**Issue by airwin** [viljamis/feature.js#49]
I found `feature.touch` is `true` in IE11, is it right?

**Comment by mynamesleon** [comment]
That's technically right. IE11 is a touch supported browser. Just bear in mind that `feature.touch` is more accurately answering the question "does this **browser** support touch?", rather than "does this **device** have touch events enabled" - detecting if a device supports touch is a very different thing

**Comment by airwin** [comment]
@mynamesleon Thanks!
